apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: frontend
        image: 688372068524.dkr.ecr.ap-south-1.amazonaws.com/capstoneproject/docker-images:frontend-9158c4ff364bdfde90fa3478bcd1d273415af654
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_BACKEND_URL
          value: "http://backend-service:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: capstone
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: NodePort
