apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      nodeSelector:
        role: frontend
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: frontend
          image: 688372068524.dkr.ecr.ap-south-1.amazonaws.com/capstoneproject/docker-images:frontend-8958dc3
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_BACKEND_URL
              value: "http://backend-service:5000"

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: capstone
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: alb        # Use ALB
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-048c063565eea401c,subnet-0fa3c62fd641c02e1"  # Public subnets for ALB
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80          # ALB listens on HTTP
      targetPort: 3000
  type: LoadBalancer
